# Generated by Django 5.1.4 on 2024-12-22 06:18

import django.db.models.deletion
import parseaudio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=parseaudio.models.OriginalAudio.original_audio_path)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_phishing', models.IntegerField(choices=[(1, '보이스피싱'), (0, '정상 통화'), (-1, '판단 어려움')])),
                ('phishing_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=parseaudio.models.SegmentAudio.segment_audio_path)),
                ('segment_index', models.IntegerField()),
                ('speaker', models.CharField(max_length=10)),
                ('transcription', models.TextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('original_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='parseaudio.originalaudio')),
            ],
        ),
    ]
