# Generated by Django 5.1.4 on 2024-12-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseaudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalaudio',
            name='is_phishing',
            field=models.IntegerField(choices=[(1, '보이스피싱'), (0, '정상 통화'), (-1, '판단 어려움')], null=True),
        ),
        migrations.AlterField(
            model_name='originalaudio',
            name='phishing_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
